name: tasks_x
description: "A 100% offline minimalist task planner app with secure local management."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_back.gif